name: Base CI
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Wrapper permissions
        run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lintKotlin

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assembleDebug